/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author adham
 */
public class TampilanUtamaKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form TampilanUtamaKaryawan
     */
    public TampilanUtamaKaryawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeButton = new javax.swing.JButton();
        JadwalShiftButton = new javax.swing.JButton();
        LKehadiranButton = new javax.swing.JButton();
        KeluarButton = new javax.swing.JButton();
        Karyawan = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomeButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, 30));

        JadwalShiftButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JadwalShiftButton.setText("Jadwal Shift");
        JadwalShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JadwalShiftButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JadwalShiftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 150, 30));

        LKehadiranButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LKehadiranButton.setText("L. Kehadiran");
        LKehadiranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LKehadiranButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LKehadiranButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 30));

        KeluarButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        KeluarButton.setText("Keluar");
        KeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(KeluarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 150, 30));

        Karyawan.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        Karyawan.setText("Karyawan");
        getContentPane().add(Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 165, 160, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TampilanUtama.png"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(841, 500));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        TampilanUtamaKaryawan tampilanutama = new TampilanUtamaKaryawan();
        tampilanutama.setVisible(true);
        tampilanutama.pack();
        tampilanutama.setLocationRelativeTo(null);
        tampilanutama.setDefaultCloseOperation(TampilanUtamaKaryawan.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void JadwalShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JadwalShiftButtonActionPerformed
        JadwalShiftKaryawan tampilanutama = new JadwalShiftKaryawan();
        tampilanutama.setVisible(true);
        tampilanutama.pack();
        tampilanutama.setLocationRelativeTo(null);
        tampilanutama.setDefaultCloseOperation(JadwalShiftKaryawan.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_JadwalShiftButtonActionPerformed

    private void LKehadiranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LKehadiranButtonActionPerformed
        LaporanKehadiranKaryawan tampilanutama = new LaporanKehadiranKaryawan();
        tampilanutama.setVisible(true);
        tampilanutama.pack();
        tampilanutama.setLocationRelativeTo(null);
        tampilanutama.setDefaultCloseOperation(LaporanKehadiranKaryawan.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_LKehadiranButtonActionPerformed

    private void KeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarButtonActionPerformed
        Login tampilanutama = new Login();
        tampilanutama.setVisible(true);
        tampilanutama.pack();
        tampilanutama.setLocationRelativeTo(null);
        tampilanutama.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_KeluarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanUtamaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanUtamaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanUtamaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanUtamaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TampilanUtamaKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton JadwalShiftButton;
    private javax.swing.JLabel Karyawan;
    private javax.swing.JButton KeluarButton;
    private javax.swing.JButton LKehadiranButton;
    // End of variables declaration//GEN-END:variables
}
